# Generated by Django 6.0.4 on 2026-04-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='anime_images/')),
                ('synopsis', models.TextField()),
                ('status', models.CharField(choices=[('airing', 'Currently Airing'), ('finished', 'Finished'), ('upcoming', 'Upcoming')], max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('tv', 'TV'), ('movie', 'Movie'), ('ova', 'OVA'), ('ona', 'ONA'), ('special', 'Special')], max_length=20)),
                ('studios', models.ManyToManyField(blank=True, to='anime.studio')),
                ('themes', models.ManyToManyField(blank=True, to='anime.theme')),
            ],
        ),
    ]
