# Generated by Django 6.0.4 on 2026-05-14 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['name'], 'verbose_name': 'Anime', 'verbose_name_plural': 'Anime'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['name'], 'verbose_name': 'Studio', 'verbose_name_plural': 'Studios'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['name'], 'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('Airing', 'Currently Airing'), ('finished', 'Finished'), ('upcoming', 'Upcoming')], max_length=20),
        ),
    ]
