# Generated by Django 6.0.4 on 2026-05-14 06:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_options_alter_studio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('text', models.TextField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='anime.anime')),
            ],
            options={
                'verbose_name': 'User Rating',
                'verbose_name_plural': 'User Ratings',
                'ordering': ['anime', 'user_name'],
            },
        ),
    ]
