# Generated by Django 6.0.4 on 2026-06-04 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_userrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrating',
            options={'ordering': ['anime', 'user'], 'verbose_name': 'User Rating', 'verbose_name_plural': 'User Ratings'},
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='user_name',
        ),
        migrations.AddField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
